//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "user")]
#[schema(example = json!({
    "id": 1,
    "username": "johndoe",
    "birthday": "2023-09-09T15:53:00Z",
    "sex": "male",
    "address": "123 Main St, Anytown, USA"
}))]
pub struct Model {
    #[sea_orm(primary_key)]
    // #[schema(example = 1)]
    pub id: i32,
    // #[schema(example = "johndoe")]
    pub username: String,
    #[schema(value_type  = String)]
    pub birthday: Option<DateTime>,
    // #[schema(example = "male")]
    pub sex: Option<String>,
    // #[schema(example = "123 Main St, Anytown, USA")]
    pub address: Option<String>,
}



#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
